# Generated by Django 5.1.1 on 2024-09-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question2', '0002_rename_usarnamae_custome_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custome_user',
            new_name='custom_user',
        ),
    ]
